/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GestionarLibros;

import Menu.Menu;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.event.ItemEvent;
import java.sql.ResultSet;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yovii
 */
public class i_gestionarLibros extends javax.swing.JFrame {

    /**
     * Creates new form i_gestionarLibro
     */
    public int posX = 0, posY = 0;
    public boolean banderaDeUsoAgregarAutor = true;
    public boolean banderaDeUsoEditarAutor = true;
    public boolean banderaDeUsoAgregarLibro = true;
    public boolean banderaDeUsoEditarLibro = true;
    private DefaultTableModel modelo = new DefaultTableModel();
    private DefaultTableModel modelo2 = new DefaultTableModel();
    public c_gestionarlibro cgl;
    public Validaciones v;

    public i_gestionarLibros() {
        initComponents();
        this.setLocationRelativeTo(null);
        modelo = (DefaultTableModel) jTLibros.getModel();
        modelo2 = (DefaultTableModel) jTAutores.getModel();
        jTBuscar.setVisible(false);
        jTBuscarLibros.setVisible(false);
        cgl = new c_gestionarlibro();
        cgl.setGestionarLibro(this);
        v = new Validaciones();

    }

    public void reiniciarColores() {
        resetColor(btn_agregarAutor);
        resetColor(btn_editarAutor);
        resetColor(btn_eliminarAutor);
        resetColor(btn_menu1);
        resetColor(btn_agregarLibro);
        resetColor(btn_editarLibro);
        resetColor(btn_eliminarLibro);
        resetColor(btn_menu);
    }

    public void setColor(JPanel jpanel) {
        jpanel.setBackground(new java.awt.Color(255, 157, 72));
    }

    public void resetColor(JPanel jpanel) {
        jpanel.setBackground(new java.awt.Color(0, 153, 204));
    }

    //Metodo que carga en la tabla todos los libros
    public void mostrarListaLibros(ResultSet listalibros) {
        limpiarTablaLibros();
        try {

            while (listalibros.next()) {
                Object row[] = new Object[7];
                for (int i = 0; i < 7; i++) {
                    row[i] = listalibros.getObject(i + 1); //El resulset los indices empiezan en 1, mi for lo empieso en 0 por eso le sumo i+1
                }
                //Agregamos cada registro al modelo de la tabla
                modelo.addRow(row);
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al cargar los datos de los libros.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

//Metodo que limpia la tabla de libros
    private void limpiarTablaLibros() {
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i -= 1;
        }
    }

    //Metodo que carga en la tabla todos los autores
    public void mostrarListaAutores(ResultSet listaAutores) {
        limpiarTablaAutores();
        try {

            while (listaAutores.next()) {
                Object row[] = new Object[4];
                for (int i = 0; i < 4; i++) {
                    row[i] = listaAutores.getObject(i + 1); //El resulset los indices empiezan en 1, mi for lo empieso en 0 por eso le sumo i+1
                }
                //Agregamos cada registro al modelo de la tabla
                modelo2.addRow(row);
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al cargar los datos de los autores.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

//Metodo que limpia la tabla de autores
    private void limpiarTablaAutores() {
        for (int i = 0; i < modelo2.getRowCount(); i++) {
            modelo2.removeRow(i);
            i -= 1;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPFondo = new javax.swing.JPanel();
        jTFondo = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        btn_agregarLibro = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_editarLibro = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_eliminarLibro = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_menu = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jCFiltrosLibros = new javax.swing.JComboBox<>();
        jTBuscarLibros = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTLibros = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        btn_agregarAutor = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btn_editarAutor = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btn_eliminarAutor = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btn_menu1 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jCFiltros = new javax.swing.JComboBox<>();
        jTBuscar = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTAutores = new javax.swing.JTable();
        jPBarra = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPFondo.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPFondoLayout = new javax.swing.GroupLayout(jPFondo);
        jPFondo.setLayout(jPFondoLayout);
        jPFondoLayout.setHorizontalGroup(
            jPFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPFondoLayout.setVerticalGroup(
            jPFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTFondo.setBackground(new java.awt.Color(255, 0, 102));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 61, 159, 10));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gestión de Libros");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 30, -1, -1));

        btn_agregarLibro.setBackground(new java.awt.Color(0, 153, 204));
        btn_agregarLibro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_agregarLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_agregarLibroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_agregarLibroMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_agregarLibroMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Agregar libro");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Add_40px.png"))); // NOI18N

        javax.swing.GroupLayout btn_agregarLibroLayout = new javax.swing.GroupLayout(btn_agregarLibro);
        btn_agregarLibro.setLayout(btn_agregarLibroLayout);
        btn_agregarLibroLayout.setHorizontalGroup(
            btn_agregarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_agregarLibroLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        btn_agregarLibroLayout.setVerticalGroup(
            btn_agregarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_agregarLibroLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(btn_agregarLibroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(btn_agregarLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 280, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Book_40px_1.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 72, -1, -1));

        btn_editarLibro.setBackground(new java.awt.Color(0, 153, 204));
        btn_editarLibro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_editarLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_editarLibroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_editarLibroMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_editarLibroMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Editar libro");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Refresh_40px.png"))); // NOI18N

        javax.swing.GroupLayout btn_editarLibroLayout = new javax.swing.GroupLayout(btn_editarLibro);
        btn_editarLibro.setLayout(btn_editarLibroLayout);
        btn_editarLibroLayout.setHorizontalGroup(
            btn_editarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_editarLibroLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addContainerGap(94, Short.MAX_VALUE))
        );
        btn_editarLibroLayout.setVerticalGroup(
            btn_editarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_editarLibroLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(btn_editarLibroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(btn_editarLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 280, 60));

        btn_eliminarLibro.setBackground(new java.awt.Color(0, 153, 204));
        btn_eliminarLibro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_eliminarLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_eliminarLibroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_eliminarLibroMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_eliminarLibroMousePressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Eliminar libro");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Delete_42px.png"))); // NOI18N

        javax.swing.GroupLayout btn_eliminarLibroLayout = new javax.swing.GroupLayout(btn_eliminarLibro);
        btn_eliminarLibro.setLayout(btn_eliminarLibroLayout);
        btn_eliminarLibroLayout.setHorizontalGroup(
            btn_eliminarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_eliminarLibroLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        btn_eliminarLibroLayout.setVerticalGroup(
            btn_eliminarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_eliminarLibroLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(btn_eliminarLibroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(btn_eliminarLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 280, 60));

        btn_menu.setBackground(new java.awt.Color(0, 153, 204));
        btn_menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_menuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_menuMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_menuMousePressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Menu");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Home_40px.png"))); // NOI18N

        javax.swing.GroupLayout btn_menuLayout = new javax.swing.GroupLayout(btn_menu);
        btn_menu.setLayout(btn_menuLayout);
        btn_menuLayout.setHorizontalGroup(
            btn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_menuLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addContainerGap(132, Short.MAX_VALUE))
        );
        btn_menuLayout.setVerticalGroup(
            btn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_menuLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(btn_menuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(btn_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 280, 60));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 640));

        jPanel4.setBackground(new java.awt.Color(0, 153, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Busqueda:");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 45, -1, -1));

        jCFiltrosLibros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un filtro", "ID", "Titulo", "Subtitulo", "Nombre autor", "Editorial" }));
        jCFiltrosLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCFiltrosLibrosActionPerformed(evt);
            }
        });
        jPanel4.add(jCFiltrosLibros, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 47, -1, -1));

        jTBuscarLibros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTBuscarLibrosKeyReleased(evt);
            }
        });
        jPanel4.add(jTBuscarLibros, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 47, 183, -1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 1010, 120));

        jTLibros.setBackground(new java.awt.Color(255, 153, 51));
        jTLibros.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jTLibros.setForeground(new java.awt.Color(255, 255, 255));
        jTLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Titulo", "Subtitulo", "Nombre autor", "Apellido autor", "Editorial", "Signatura"
            }
        ));
        jTLibros.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTLibros);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 1010, 520));

        jTFondo.addTab("Libros", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(0, 153, 204));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 61, 159, 10));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Gestión de Autores");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        btn_agregarAutor.setBackground(new java.awt.Color(0, 153, 204));
        btn_agregarAutor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_agregarAutor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_agregarAutorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_agregarAutorMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_agregarAutorMousePressed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Agregar autor");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Add_40px.png"))); // NOI18N

        javax.swing.GroupLayout btn_agregarAutorLayout = new javax.swing.GroupLayout(btn_agregarAutor);
        btn_agregarAutor.setLayout(btn_agregarAutorLayout);
        btn_agregarAutorLayout.setHorizontalGroup(
            btn_agregarAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_agregarAutorLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        btn_agregarAutorLayout.setVerticalGroup(
            btn_agregarAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_agregarAutorLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(btn_agregarAutorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.add(btn_agregarAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 280, 60));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_User_Typing_Using_Typewriter_40px.png"))); // NOI18N
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 72, -1, -1));

        btn_editarAutor.setBackground(new java.awt.Color(0, 153, 204));
        btn_editarAutor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_editarAutor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_editarAutorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_editarAutorMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_editarAutorMousePressed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Editar autor");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Refresh_40px.png"))); // NOI18N

        javax.swing.GroupLayout btn_editarAutorLayout = new javax.swing.GroupLayout(btn_editarAutor);
        btn_editarAutor.setLayout(btn_editarAutorLayout);
        btn_editarAutorLayout.setHorizontalGroup(
            btn_editarAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_editarAutorLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addContainerGap(90, Short.MAX_VALUE))
        );
        btn_editarAutorLayout.setVerticalGroup(
            btn_editarAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_editarAutorLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(btn_editarAutorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.add(btn_editarAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 280, 60));

        btn_eliminarAutor.setBackground(new java.awt.Color(0, 153, 204));
        btn_eliminarAutor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_eliminarAutor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_eliminarAutorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_eliminarAutorMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_eliminarAutorMousePressed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Eliminar autor");

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Delete_42px.png"))); // NOI18N

        javax.swing.GroupLayout btn_eliminarAutorLayout = new javax.swing.GroupLayout(btn_eliminarAutor);
        btn_eliminarAutor.setLayout(btn_eliminarAutorLayout);
        btn_eliminarAutorLayout.setHorizontalGroup(
            btn_eliminarAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_eliminarAutorLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        btn_eliminarAutorLayout.setVerticalGroup(
            btn_eliminarAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_eliminarAutorLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(btn_eliminarAutorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.add(btn_eliminarAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 280, 60));

        btn_menu1.setBackground(new java.awt.Color(0, 153, 204));
        btn_menu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_menu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_menu1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_menu1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_menu1MousePressed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Menu");

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Home_40px.png"))); // NOI18N

        javax.swing.GroupLayout btn_menu1Layout = new javax.swing.GroupLayout(btn_menu1);
        btn_menu1.setLayout(btn_menu1Layout);
        btn_menu1Layout.setHorizontalGroup(
            btn_menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_menu1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addContainerGap(132, Short.MAX_VALUE))
        );
        btn_menu1Layout.setVerticalGroup(
            btn_menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_menu1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(btn_menu1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.add(btn_menu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 280, 60));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 640));

        jPanel6.setBackground(new java.awt.Color(0, 153, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Busqueda:");
        jPanel6.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 45, -1, -1));

        jCFiltros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un filtro", "ID", "Nombre", "Primer apellido" }));
        jCFiltros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCFiltrosActionPerformed(evt);
            }
        });
        jPanel6.add(jCFiltros, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 47, -1, -1));

        jTBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTBuscarKeyReleased(evt);
            }
        });
        jPanel6.add(jTBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 47, 155, -1));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 1010, 120));

        jTAutores.setBackground(new java.awt.Color(255, 153, 51));
        jTAutores.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jTAutores.setForeground(new java.awt.Color(255, 255, 255));
        jTAutores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Primer apellido", "Segundo apellido"
            }
        ));
        jScrollPane2.setViewportView(jTAutores);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 1010, 520));

        jTFondo.addTab("Autores", jPanel3);

        jPBarra.setBackground(new java.awt.Color(102, 102, 102));
        jPBarra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPBarraMouseDragged(evt);
            }
        });
        jPBarra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPBarraMousePressed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Gestión de libros y autores");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Delete_32px_1.png"))); // NOI18N
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel21MousePressed(evt);
            }
        });

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Expand_Arrow_32px_1.png"))); // NOI18N

        javax.swing.GroupLayout jPBarraLayout = new javax.swing.GroupLayout(jPBarra);
        jPBarra.setLayout(jPBarraLayout);
        jPBarraLayout.setHorizontalGroup(
            jPBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPBarraLayout.createSequentialGroup()
                .addGap(457, 457, 457)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21))
        );
        jPBarraLayout.setVerticalGroup(
            jPBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBarraLayout.createSequentialGroup()
                .addGroup(jPBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel26)
                    .addGroup(jPBarraLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel25)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 1296, Short.MAX_VALUE)
            .addComponent(jPBarra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_agregarLibroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregarLibroMousePressed
        setColor(btn_agregarLibro);
        resetColor(btn_editarLibro);
        resetColor(btn_menu);
        resetColor(btn_eliminarLibro);
        if(this.banderaDeUsoAgregarLibro)
        {
        c_agregarlibro cal = new c_agregarlibro();
        cal.setInterfazGestionarLibro(this);
        cal.prepararInterfazAgregarLibro();
        this.banderaDeUsoAgregarLibro = false;
        }
    }//GEN-LAST:event_btn_agregarLibroMousePressed

    private void btn_editarLibroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editarLibroMousePressed
        setColor(btn_editarLibro);
        resetColor(btn_agregarLibro);
        resetColor(btn_menu);
        resetColor(btn_eliminarLibro);
        if (jTLibros.getSelectedRow() != -1) {
            if(this.banderaDeUsoEditarLibro)
            {
            c_editarLibro cel = new c_editarLibro();
            cel.setInterfazGestionarLibro(this);
            String ID = String.valueOf(jTLibros.getValueAt(jTLibros.getSelectedRow(), 0));
            cel.buscarDatosLibro(ID);
            cel.prepararInterfazEditarLibro();
            this.banderaDeUsoEditarLibro = false;
            }
            
        } else {
            JOptionPane.showMessageDialog(null, "No ha seleccionado ninguna fila");
            reiniciarColores();

        }// TODO add your handling code here:
    }//GEN-LAST:event_btn_editarLibroMousePressed

    private void btn_eliminarLibroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarLibroMousePressed
        setColor(btn_eliminarLibro);
        resetColor(btn_agregarLibro);
        resetColor(btn_menu);
        resetColor(btn_editarLibro);
        if (jTLibros.getSelectedRow() != -1) {
            cgl.setGestionarLibro(this);
            String ID = String.valueOf(jTLibros.getValueAt(jTLibros.getSelectedRow(), 0));
            cgl.eliminarLibro(ID);
        } else {
            JOptionPane.showMessageDialog(null, "No ha seleccionado ninguna fila");
            reiniciarColores();
        }// TODO add your handling code here:
    }//GEN-LAST:event_btn_eliminarLibroMousePressed

    private void btn_menuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menuMousePressed
        setColor(btn_menu);
        resetColor(btn_agregarLibro);
        resetColor(btn_eliminarLibro);
        resetColor(btn_editarLibro);
        Menu me = new Menu();
        me.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btn_menuMousePressed

    private void btn_agregarAutorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregarAutorMousePressed
        setColor(btn_agregarAutor);
        resetColor(btn_editarAutor);
        resetColor(btn_menu1);
        resetColor(btn_eliminarAutor);
        if (this.banderaDeUsoAgregarAutor) {
            c_agregarAutor caa = new c_agregarAutor();
            caa.setInterfazGestionarLibro(this);
            caa.prepararInterfazAgregarAutor();
            this.banderaDeUsoAgregarAutor = false;
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_agregarAutorMousePressed

    private void btn_editarAutorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editarAutorMousePressed
        setColor(btn_editarAutor);
        resetColor(btn_agregarAutor);
        resetColor(btn_menu1);
        resetColor(btn_eliminarAutor);
        if (jTAutores.getSelectedRow() != -1) {
            if (this.banderaDeUsoEditarAutor) {
                c_editarAutor cea = new c_editarAutor();
                cea.setInterfazGestionarLibro(this);
                String ID = String.valueOf(jTAutores.getValueAt(jTAutores.getSelectedRow(), 0));
                String nombre = String.valueOf(jTAutores.getValueAt(jTAutores.getSelectedRow(), 1));
                String primero = String.valueOf(jTAutores.getValueAt(jTAutores.getSelectedRow(), 2));
                String segundo = String.valueOf(jTAutores.getValueAt(jTAutores.getSelectedRow(), 3));
                cea.prepararInterfazEditarAutor(ID, nombre, primero, segundo);
                this.banderaDeUsoEditarAutor = false;
            }

        } else {
            JOptionPane.showMessageDialog(null, "No ha seleccionado ninguna fila");
            reiniciarColores();

        }// TODO add your handling code here:
    }//GEN-LAST:event_btn_editarAutorMousePressed

    private void btn_eliminarAutorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarAutorMousePressed
        setColor(btn_eliminarAutor);
        resetColor(btn_agregarAutor);
        resetColor(btn_menu1);
        resetColor(btn_editarAutor);
        if (jTAutores.getSelectedRow() != -1) {
            cgl.setGestionarLibro(this);
            String ID = String.valueOf(jTAutores.getValueAt(jTAutores.getSelectedRow(), 0));
            cgl.eliminarAutor(ID);
        } else {
            JOptionPane.showMessageDialog(null, "No ha seleccionado ninguna fila");
            reiniciarColores();
        }// TODO add your handling code here:
    }//GEN-LAST:event_btn_eliminarAutorMousePressed

    private void btn_menu1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menu1MousePressed
        setColor(btn_menu1);
        resetColor(btn_agregarAutor);
        resetColor(btn_eliminarAutor);
        resetColor(btn_editarAutor);
        Menu me = new Menu();
        me.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btn_menu1MousePressed

    private void jLabel21MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MousePressed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel21MousePressed

    private void jCFiltrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCFiltrosActionPerformed

        if (this.jCFiltros.getSelectedItem().equals("Seleccione un filtro")) {
            this.jTBuscar.setVisible(false);

            //this.jTextField2.setVisible(falso);
        } else {
            jTBuscar.setText("");
            this.jTBuscar.setVisible(true);
            jTBuscar.requestFocus();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jCFiltrosActionPerformed

    private void btn_agregarAutorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregarAutorMouseEntered
        setColor(btn_agregarAutor);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_agregarAutorMouseEntered

    private void btn_agregarAutorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregarAutorMouseExited
        resetColor(btn_agregarAutor);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_agregarAutorMouseExited

    private void btn_editarAutorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editarAutorMouseEntered
        setColor(btn_editarAutor);   // TODO add your handling code here:
    }//GEN-LAST:event_btn_editarAutorMouseEntered

    private void btn_editarAutorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editarAutorMouseExited
        resetColor(btn_editarAutor);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_editarAutorMouseExited

    private void btn_eliminarAutorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarAutorMouseEntered
        setColor(btn_eliminarAutor);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_eliminarAutorMouseEntered

    private void btn_eliminarAutorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarAutorMouseExited
        resetColor(btn_eliminarAutor);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_eliminarAutorMouseExited

    private void btn_menu1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menu1MouseEntered
        setColor(btn_menu1);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_menu1MouseEntered

    private void btn_menu1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menu1MouseExited
        resetColor(btn_menu1);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_menu1MouseExited

    private void jTBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTBuscarKeyReleased
        String busq = this.jTBuscarLibros.getText();

        //creo un objeto de tipo patron para verifcar el lenguaje que 
        //voy a usar en lo sera el modulo de buscar por id
        Pattern patron = Pattern.compile("[0-9]*");

        //compruebo que busq pertenezca al lenguaje
        Matcher m = patron.matcher(busq);

        //esto retorna un booleano para ver si busq se encuentra dentro
        //del lenguaje
        boolean b = m.matches();

        if (jTBuscar.getText().length() != 0) {
            if (jCFiltros.getSelectedItem().equals("ID")) {
                if (b) {

                    this.cgl.buscarIDAutor(busq);
                } else {
                    this.cgl.recargarListaAutores();
                }

            }

            if (jCFiltros.getSelectedItem().equals("Nombre")) {
                cgl.buscarNombreAutor(jTBuscar.getText());
            }
            if (jCFiltros.getSelectedItem().equals("Primer apellido")) {
                cgl.buscarPrimerApellidoAutor(jTBuscar.getText());
            }
        } else {
            cgl.recargarListaAutores();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jTBuscarKeyReleased

    private void btn_agregarLibroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregarLibroMouseEntered
        setColor(btn_agregarLibro);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_agregarLibroMouseEntered

    private void btn_agregarLibroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregarLibroMouseExited
        resetColor(btn_agregarLibro);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_agregarLibroMouseExited

    private void btn_editarLibroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editarLibroMouseEntered
        setColor(btn_editarLibro);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_editarLibroMouseEntered

    private void btn_editarLibroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editarLibroMouseExited
        resetColor(btn_editarLibro);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_editarLibroMouseExited

    private void btn_eliminarLibroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarLibroMouseEntered
        setColor(btn_eliminarLibro);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_eliminarLibroMouseEntered

    private void btn_eliminarLibroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarLibroMouseExited
        resetColor(btn_eliminarLibro);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_eliminarLibroMouseExited

    private void btn_menuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menuMouseEntered
        setColor(btn_menu);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_menuMouseEntered

    private void btn_menuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menuMouseExited
        resetColor(btn_menu);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_menuMouseExited

    private void jPBarraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPBarraMousePressed
        this.posX = evt.getX();
        this.posY = evt.getY();// TODO add your handling code here:
    }//GEN-LAST:event_jPBarraMousePressed

    private void jPBarraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPBarraMouseDragged
        Point point = MouseInfo.getPointerInfo().getLocation();
        int x = point.x - this.posX;
        int y = point.y - this.posY;
        this.setLocation(x, y);

// TODO add your handling code here:
    }//GEN-LAST:event_jPBarraMouseDragged

    private void jTBuscarLibrosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTBuscarLibrosKeyReleased

        String busq = this.jTBuscarLibros.getText();

        //creo un objeto de tipo patron para verifcar el lenguaje que 
        //voy a usar en lo sera el modulo de buscar por id
        Pattern patron = Pattern.compile("[0-9]*");

        //compruebo que busq pertenezca al lenguaje
        Matcher m = patron.matcher(busq);

        //esto retorna un booleano para ver si busq se encuentra dentro
        //del lenguaje
        boolean b = m.matches();

        if (jTBuscarLibros.getText().length() != 0) {
            if (jCFiltrosLibros.getSelectedItem().equals("ID")) {
                if (b) {

                    this.cgl.buscarIDLibro(busq);
                } else {
                    this.cgl.recargarListaLibros();
                }
            }
            //Este no funciona
            if (jCFiltrosLibros.getSelectedItem().equals("Titulo")) {
                cgl.buscarTituloLibro(jTBuscarLibros.getText());
            }
            if (jCFiltrosLibros.getSelectedItem().equals("Subtitulo")) {
                cgl.buscarSubtituloLibro(jTBuscarLibros.getText());
            }
            if (jCFiltrosLibros.getSelectedItem().equals("Nombre autor")) {
                cgl.buscarNombreAutorLibro(jTBuscarLibros.getText());
            }
            if (jCFiltrosLibros.getSelectedItem().equals("Editorial")) {
                cgl.buscarEditorialLibro(jTBuscarLibros.getText());
            }
        } else {
            cgl.recargarListaLibros();
        }// TODO add your handling code here:
    }//GEN-LAST:event_jTBuscarLibrosKeyReleased

    private void jCFiltrosLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCFiltrosLibrosActionPerformed
        if (this.jCFiltrosLibros.getSelectedItem().equals("Seleccione un filtro")) {
            this.jTBuscarLibros.setVisible(false);

            //this.jTextField2.setVisible(falso);
        } else {
            jTBuscarLibros.setText("");
            this.jTBuscarLibros.setVisible(true);
            jTBuscarLibros.requestFocus();
        }        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_jCFiltrosLibrosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(i_gestionarLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(i_gestionarLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(i_gestionarLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(i_gestionarLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new i_gestionarLibros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_agregarAutor;
    private javax.swing.JPanel btn_agregarLibro;
    private javax.swing.JPanel btn_editarAutor;
    private javax.swing.JPanel btn_editarLibro;
    private javax.swing.JPanel btn_eliminarAutor;
    private javax.swing.JPanel btn_eliminarLibro;
    private javax.swing.JPanel btn_menu;
    private javax.swing.JPanel btn_menu1;
    private javax.swing.JComboBox<String> jCFiltros;
    private javax.swing.JComboBox<String> jCFiltrosLibros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPBarra;
    private javax.swing.JPanel jPFondo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTAutores;
    private javax.swing.JTextField jTBuscar;
    private javax.swing.JTextField jTBuscarLibros;
    private javax.swing.JTabbedPane jTFondo;
    private javax.swing.JTable jTLibros;
    // End of variables declaration//GEN-END:variables
}
