/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GestionarUsuarios;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Elmer Yam
 */
public class i_editarUsuario extends javax.swing.JFrame {

    c_agregarUsuario cau;
    Date fecha;
    private i_gestionarUsuarios Usuario;

    /**
     * Creates new form agregarlibro
     */
    public i_editarUsuario() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.deshabilitarCampos();
        this.validaciones();
        fecha = new Date();
        this.jtMatricula.setEditable(false);
    }
    public void mostrarDatosUsuario(ResultSet datosUsuario){
     
        try {
          
            this.jtMatricula.setText(datosUsuario.getString("usuario_id"));
             this.jtNombre.setText(datosUsuario.getString("usuario_nombre"));
            
           
        } catch (SQLException ex) {
            Logger.getLogger(i_editarUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
               
                /*this.jtPaterno.setText(datos.getString("personal_apaterno"));
                this.jtMaterno.setText(datos.getString("personal_amaterno"));
                this.jtCalle.setText(datos.getString("personal_calle"));
                this.jtTelefono.setText(datos.getString("personal_telefono"));
                this.jtColonia.setText(datos.getString("personal_colonia"));
                this.jtUsuario.setText(datos.getString("personal_usuario"));
                this.jtPassword.setText(datos.getString("personal_password"));
                this.jComboBox1.setSelectedItem(datos.getString("personal_tipopersonal"));*/
        
        
    }
    public void deshabilitarCampos(){
        jtMatricula.setEnabled(false);
        jtNombre.setEnabled(false);
        jtApaterno.setEnabled(false);
        jtAmaterno.setEnabled(false);
        jtFehaNac.setEnabled(false);
        jtCorreo.setEnabled(false);
        jtTelefono.setEnabled(false);
        jtColonia.setEnabled(false);
        jtCalle.setEnabled(false);
        jtCruzamiento1.setEnabled(false);
        jtCruzamiento2.setEnabled(false);
        jtNumCasa.setEnabled(false);
        jtLugarTrabajo.setEnabled(false);
        jtPuestoTrabajo.setEnabled(false);
    }
    public void habilitarCampos(){
        if(jcbTipoUsuario.getSelectedItem().equals("Alumno"))
        {
        jtMatricula.setEnabled(true);
        jtNombre.setEnabled(true);
        jtApaterno.setEnabled(true);
        jtAmaterno.setEnabled(true);
        jtFehaNac.setEnabled(true);
        jtCorreo.setEnabled(true);
        jtTelefono.setEnabled(true);
        jtColonia.setEnabled(true);
        jtCalle.setEnabled(true);
        jtCruzamiento1.setEnabled(true);
        jtCruzamiento2.setEnabled(true);
        jtNumCasa.setEnabled(true);
        jtLugarTrabajo.setEnabled(false);
        jtPuestoTrabajo.setEnabled(false);
        jtLugarTrabajo.setText("");
        jtPuestoTrabajo.setText("");
        }
        if(jcbTipoUsuario.getSelectedItem().equals("Seleccione Tipo"))
        {
            this.deshabilitarCampos();
            limpiarCampos();
        }
        if(jcbTipoUsuario.getSelectedItem().equals("Externo"))
        {
        jtMatricula.setEnabled(false);
        jtMatricula.setText("");
        jtNombre.setEnabled(true);
        jtApaterno.setEnabled(true);
        jtAmaterno.setEnabled(true);
        jtFehaNac.setEnabled(true);
        jtCorreo.setEnabled(true);
        jtTelefono.setEnabled(true);
        jtColonia.setEnabled(true);
        jtCalle.setEnabled(true);
        jtCruzamiento1.setEnabled(true);
        jtCruzamiento2.setEnabled(true);
        jtNumCasa.setEnabled(true);
        jtLugarTrabajo.setEnabled(true);
        jtPuestoTrabajo.setEnabled(true);
        }
     
    }
    public void desplegarInterfazAgregarUsuario() {
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtAmaterno = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtApaterno = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jtMatricula = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jtCorreo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jtTelefono = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jcbTipoUsuario = new javax.swing.JComboBox<>();
        jtFehaNac = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jtColonia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtCalle = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jtNumCasa = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jtCruzamiento1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jtCruzamiento2 = new javax.swing.JTextField();
        jPDatosLab = new javax.swing.JPanel();
        jlLugarTrabajo = new javax.swing.JLabel();
        jtLugarTrabajo = new javax.swing.JTextField();
        jlPuestoTrabajo = new javax.swing.JLabel();
        jtPuestoTrabajo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Editar usuario");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(345, 345, 345)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Save_48px.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Cancel_48px.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel8MousePressed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Personales"));

        jtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNombreActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre:");

        jLabel3.setText("Primer Apellido:");

        jLabel9.setText("Segundo Apellido:");

        jLabel17.setText("Matricula:");

        jtMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtMatriculaActionPerformed(evt);
            }
        });

        jLabel11.setText("Fecha de Nacimiento:");

        jLabel13.setText("Correo Electronico:");

        jLabel12.setText("Telefono:");

        jLabel20.setText("Tipo de Usuario:");

        jcbTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alumno", "Externo" }));
        jcbTipoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTipoUsuarioActionPerformed(evt);
            }
        });

        jtFehaNac.setDateFormatString("dd/MMM/yyyy");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13)
                                .addComponent(jLabel11)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel9))
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtApaterno)
                                    .addComponent(jtAmaterno)
                                    .addComponent(jtCorreo)
                                    .addComponent(jcbTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtFehaNac, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtApaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtAmaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jtFehaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Domiciliarios"));

        jLabel4.setText("Colonia:");

        jLabel5.setText("Calle:");

        jLabel14.setText("Numero de Casa:");

        jLabel15.setText("Cruzamiento 1");

        jtCruzamiento1.setToolTipText("Primera Calle");

        jLabel16.setText("Cruzamiento 2:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtCalle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtColonia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(32, 32, 32)
                                .addComponent(jtCruzamiento1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(182, 182, 182))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtCruzamiento2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtNumCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtColonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jtCruzamiento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jtCruzamiento2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jtNumCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jPDatosLab.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Laborales"));

        jlLugarTrabajo.setText("Lugar de trabajo:");

        jlPuestoTrabajo.setText("Puesto:");

        javax.swing.GroupLayout jPDatosLabLayout = new javax.swing.GroupLayout(jPDatosLab);
        jPDatosLab.setLayout(jPDatosLabLayout);
        jPDatosLabLayout.setHorizontalGroup(
            jPDatosLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDatosLabLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPDatosLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlPuestoTrabajo)
                    .addComponent(jlLugarTrabajo))
                .addGap(18, 18, 18)
                .addGroup(jPDatosLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtLugarTrabajo, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                    .addComponent(jtPuestoTrabajo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPDatosLabLayout.setVerticalGroup(
            jPDatosLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDatosLabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPDatosLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtLugarTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlLugarTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPDatosLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtPuestoTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlPuestoTrabajo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPDatosLab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPDatosLab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MousePressed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MousePressed

    private void jtMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtMatriculaActionPerformed
    
    //Metodo que se ejecuta para actulizar a un usuario en la base de datos
    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed
        //crea un objeto de tipo c_agregarUsuario
        c_agregarUsuario obj_cau = new c_agregarUsuario();
        //agregamos todos los datos a sus variables
        
        String tipoUsuario = (String) this.jcbTipoUsuario.getSelectedItem();
        String matricula = this.jtMatricula.getText();
        String nombre = this.jtNombre.getText();
        String primerA = this.jtApaterno.getText();
        String segundoA = this.jtAmaterno.getText();
        String calle = this.jtCalle.getText();
        Date date = this.jtFehaNac.getDate();
        long d = date.getTime();
        java.sql.Date fecha = new java.sql.Date(d);
        String correo = this.jtCorreo.getText();
        String telefono = this.jtTelefono.getText();
        String colonia = this.jtColonia.getText();
        String cruzamiento1 = this.jtCruzamiento1.getText();
        String cruzamiento2 = this.jtCruzamiento2.getText();
        String numCasa = this.jtNumCasa.getText();
        String lugarTrabajo = this.jtLugarTrabajo.getText();
        String puestoTrabajo = this.jtPuestoTrabajo.getText();
        //llama al metodo actulizarRegistro del objeto creado si el tipo es alumno
        if(this.jcbTipoUsuario.getSelectedItem().equals("Alumno")){
          //  mensajeroControlUsu.guardarRegistroAlumno(tipoUsuario, matricula, nombre, primerA, segundoA,
            //    fecha, correo, telefono, colonia, calle, cruzamiento1, cruzamiento2, numCasa);
        }
        //si el tipo es externo llama al metodo guardarRegistroExterno
        if(this.jcbTipoUsuario.getSelectedItem().equals("Externo")){
            //mensajeroControlUsu.guardarRegistroExterno(tipoUsuario, nombre, primerA, segundoA, fecha, correo, telefono, colonia, calle, cruzamiento1, cruzamiento2, numCasa, lugarTrabajo, puestoTrabajo);
        }
        else{
            //mensajeroControlUsu.guardarRegistroAlumno(correo, matricula, nombre, telefono, telefono, date, correo, telefono, colonia, calle, correo, correo, numCasa);
        }
        
    }//GEN-LAST:event_jLabel6MousePressed

    //metodo que se ejecuta cuando es seleccionado el tipo de usuario
    private void jcbTipoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTipoUsuarioActionPerformed

       habilitarCampos();
    }//GEN-LAST:event_jcbTipoUsuarioActionPerformed

    private void jtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNombreActionPerformed
       //metodo para mandar valores vacios a los campos del formulario
    public void limpiarCampos() {
        this.jcbTipoUsuario.setSelectedItem("Seleccione Tipo");
        this.jtMatricula.setText("");
        this.jtNombre.setText("");
        this.jtApaterno.setText("");
        this.jtAmaterno.setText("");
        this.jtFehaNac.setDateFormatString("");
        this.jtCorreo.setText("");
        this.jtTelefono.setText("");
        this.jtColonia.setText("");
        this.jtCalle.setText("");
        this.jtNumCasa.setText("");
        this.jtLugarTrabajo.setText("");
        this.jtPuestoTrabajo.setText("");
    }

    public void validaciones() {
        validacionUsuario v = new validacionUsuario();
        //validando matricula
        v.validarNumeros(jtMatricula);
        v.limitarCaracteres(jtMatricula, 8);
        //validando nombre
        v.validarLetras(jtNombre);
        v.limitarCaracteres(jtNombre, 20);
        //validando primer apellido
        v.validarLetras(jtApaterno);
        v.limitarCaracteres(jtApaterno, 20);
        //validando segundo apellido
        v.validarLetras(jtAmaterno);
        v.limitarCaracteres(jtAmaterno, 20);
        //validando fecha
        //validando telefono
        v.validarNumeros(jtTelefono);
        v.limitarCaracteres(jtTelefono, 10);
        //validar colonia
        v.limitarCaracteres(jtColonia, 30);
        //validar calle
        v.limitarCaracteres(jtCalle, 30);
        //validar cruzamientos uno
        v.limitarCaracteres(jtCruzamiento1, 30);
        //validar cruzamiento dos
        v.limitarCaracteres(jtCruzamiento2, 30);
        //validar numero de casa
        v.limitarCaracteres(jtNumCasa, 12);
        // validar lugar de trabajo
        v.validarLetras(jtLugarTrabajo);
        v.limitarCaracteres(jtLugarTrabajo, 20);
        //validar puesto de trabajo
        v.validarLetras(jtPuestoTrabajo);
        v.limitarCaracteres(jtPuestoTrabajo, 10);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(i_editarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(i_editarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(i_editarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(i_editarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new i_editarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPDatosLab;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JComboBox<String> jcbTipoUsuario;
    private javax.swing.JLabel jlLugarTrabajo;
    private javax.swing.JLabel jlPuestoTrabajo;
    private javax.swing.JTextField jtAmaterno;
    private javax.swing.JTextField jtApaterno;
    private javax.swing.JTextField jtCalle;
    private javax.swing.JTextField jtColonia;
    private javax.swing.JTextField jtCorreo;
    private javax.swing.JTextField jtCruzamiento1;
    private javax.swing.JTextField jtCruzamiento2;
    private com.toedter.calendar.JDateChooser jtFehaNac;
    private javax.swing.JTextField jtLugarTrabajo;
    private javax.swing.JTextField jtMatricula;
    private javax.swing.JTextField jtNombre;
    private javax.swing.JTextField jtNumCasa;
    private javax.swing.JTextField jtPuestoTrabajo;
    private javax.swing.JTextField jtTelefono;
    // End of variables declaration//GEN-END:variables

    public void setEditarPersonal(i_gestionarUsuarios iep) {
        this.Usuario = iep;
    }
    
    //este metodo manda los valores a la pantalla de editar
    public void cargarDatosPersonal(ResultSet rs) {
        try {
            while (rs.next()) {
                this.jcbTipoUsuario.setSelectedItem(rs.getString("usuario_tipo"));
                this.jtMatricula.setText(rs.getString("usuario_id"));
                this.jtNombre.setText(rs.getString("usuario_nombre"));
                this.jtApaterno.setText(rs.getString("usuario_primer_apellido"));
                this.jtAmaterno.setText(rs.getString("usuario_segundo_apellido"));
                this.jtFehaNac.setDate(rs.getDate("usuario_fecha"));
                this.jtCalle.setText(rs.getString("usuario_calle"));
                this.jtCorreo.setText(rs.getString("usuario_correo"));
                this.jtTelefono.setText(rs.getString("usuario_telefono"));
                this.jtColonia.setText(rs.getString("usuario_colonia"));
                this.jtCalle.setText(rs.getString("usuario_calle"));
                this.jtCruzamiento1.setText(rs.getString("usuario_cruzamiento1"));
                this.jtCruzamiento2.setText(rs.getString("usuario_cruzamiento2"));
                this.jtNumCasa.setText(rs.getString("usuario_numcasa"));
                this.jtLugarTrabajo.setText(rs.getString("usuario_trabajo"));
                this.jtPuestoTrabajo.setText(rs.getString("usuario_puesto"));
            }
        } catch (Exception e) {
            System.out.println("falló");
            e.printStackTrace();
        }
    }

 


}
