/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GestionarUsuarios;

import Menu.Menu;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yovii
 */
public class i_gestionarUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form GestionarLibros
     */
    private DefaultTableModel modelo = new DefaultTableModel();
    c_gestionarUsuario menUsua;

    int i = 0;

    //metodo constructor
    public i_gestionarUsuarios() {
        initComponents();
        this.setLocationRelativeTo(null);
        modelo = (DefaultTableModel) jTUsuarios.getModel();
        this.menUsua = new c_gestionarUsuario();
        this.menUsua.setGestionarUsuarios(this);
        //this.validaciones();

    }

    //Este metodo carga datos en la tabla
    public void mostrarListaUsuarios(ResultSet listaUsuarios) {
        limpiarTabla();
        try {

            while (listaUsuarios.next()) {
                Object row[] = new Object[4];
                for (int i = 0; i < 4; i++) {
                    row[i] = listaUsuarios.getObject(i + 1); //El resulset los indices empiezan en 1, mi for lo empieso en 0 por eso le sumo i+1
                }
                //Agregamos cada registro al modelo de la tabla
                modelo.addRow(row);
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al cargar los datos de los usuarios.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Este metodo limpia la tabla para ingresar nuevos datos
    private void limpiarTabla() {
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i -= 1;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jtBuscar = new javax.swing.JTextField();
        jcbFiltros = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        btn_agregar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_editar = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_eliminar = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btn_menu = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTUsuarios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 230, 10));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Search_30px.png"))); // NOI18N
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        jtBuscar.setBackground(new java.awt.Color(0, 153, 204));
        jtBuscar.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jtBuscar.setForeground(new java.awt.Color(255, 255, 255));
        jtBuscar.setBorder(null);
        jtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtBuscarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtBuscarKeyTyped(evt);
            }
        });
        jPanel1.add(jtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 230, 20));

        jcbFiltros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matricula", "Nombre", "Primer Apellido" }));
        jcbFiltros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbFiltrosActionPerformed(evt);
            }
        });
        jPanel1.add(jcbFiltros, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 120, 20));

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_agregar.setBackground(new java.awt.Color(0, 153, 204));
        btn_agregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_agregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_agregarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_agregarMousePressed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Add_40px.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Agregar Usuario");
        jLabel5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel5KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout btn_agregarLayout = new javax.swing.GroupLayout(btn_agregar);
        btn_agregar.setLayout(btn_agregarLayout);
        btn_agregarLayout.setHorizontalGroup(
            btn_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_agregarLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addGap(47, 47, 47)
                .addComponent(jLabel5)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        btn_agregarLayout.setVerticalGroup(
            btn_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_agregarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(btn_agregarLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(btn_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 270, -1));

        btn_editar.setBackground(new java.awt.Color(0, 153, 204));
        btn_editar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_editarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_editarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_editarMousePressed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Refresh_40px.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Editar Usuario");

        javax.swing.GroupLayout btn_editarLayout = new javax.swing.GroupLayout(btn_editar);
        btn_editar.setLayout(btn_editarLayout);
        btn_editarLayout.setHorizontalGroup(
            btn_editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_editarLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel6)
                .addGap(47, 47, 47)
                .addComponent(jLabel7)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        btn_editarLayout.setVerticalGroup(
            btn_editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_editarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(btn_editarLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(btn_editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 270, -1));

        btn_eliminar.setBackground(new java.awt.Color(0, 153, 204));
        btn_eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_eliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_eliminarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_eliminarMousePressed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Delete_42px.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Eliminar Usuario");

        javax.swing.GroupLayout btn_eliminarLayout = new javax.swing.GroupLayout(btn_eliminar);
        btn_eliminar.setLayout(btn_eliminarLayout);
        btn_eliminarLayout.setHorizontalGroup(
            btn_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_eliminarLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel8)
                .addGap(47, 47, 47)
                .addComponent(jLabel9)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        btn_eliminarLayout.setVerticalGroup(
            btn_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_eliminarLayout.createSequentialGroup()
                .addGroup(btn_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btn_eliminarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(btn_eliminarLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel9)))
                .addContainerGap())
        );

        jPanel2.add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 270, 60));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Gestión de Usuarios");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 52, 190, 10));

        btn_menu.setBackground(new java.awt.Color(0, 153, 204));
        btn_menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_menuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_menuMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_menuMousePressed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Home_40px.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Menú");

        javax.swing.GroupLayout btn_menuLayout = new javax.swing.GroupLayout(btn_menu);
        btn_menu.setLayout(btn_menuLayout);
        btn_menuLayout.setHorizontalGroup(
            btn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_menuLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel10)
                .addGap(54, 54, 54)
                .addComponent(jLabel11)
                .addContainerGap(115, Short.MAX_VALUE))
        );
        btn_menuLayout.setVerticalGroup(
            btn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_menuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(btn_menuLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(btn_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 270, 60));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jTUsuarios.setBackground(new java.awt.Color(255, 255, 204));
        jTUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Anatomia", "Yo", "Trillas"},
                {"2", "Matematicas", "Tu", "Santillana"},
                {"3", "Fisica", "Ella", "Mex"},
                {"4", "Español", "Nosotros", "Yam"},
                {null, null, null, null}
            },
            new String [] {
                "Matricula", "Nombre", "Primer Apellido", "Segundo Apellido"
            }
        ));
        jTUsuarios.setShowHorizontalLines(false);
        jTUsuarios.setShowVerticalLines(false);
        jScrollPane1.setViewportView(jTUsuarios);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //metodo que se ejecuta cuando se presiona el boton agregar usuario
    private void btn_agregarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregarMousePressed
        setColor(btn_agregar);
        resetColor(btn_editar);
        resetColor(btn_eliminar);
        resetColor(btn_menu);
     
        c_agregarUsuario mensajeroC_AU = new c_agregarUsuario();
        mensajeroC_AU.setInterfazGestionarUsuario(this);
        mensajeroC_AU.prepararInterfazAgregarUsuario();
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_agregarMousePressed

    //Este metodo se ejecuta cuando hacemos click sobre el boton editar
    private void btn_editarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editarMousePressed
        //obtiene el fila seleccionada
        int seleccion = this.jTUsuarios.getSelectedRow();
        //si hay una fila seleccionada se ejecuta el siguiete codigo
        if (seleccion != -1) {
            //enviamos el objeto a nuestro control
            c_editarUsuario obj_cEditarUsuario = new c_editarUsuario();
            obj_cEditarUsuario.setEditarPersonal(this);
            //Obtenemos la matricula 
            String matricula = String.valueOf(jTUsuarios.getValueAt(seleccion, 0));
            //preparamos la interfaz y la mostramos
            obj_cEditarUsuario.obtenerDatosUsuario(matricula);
            obj_cEditarUsuario.prepararInterfazEditarUsuario();
        } else {
            //se manda un mensaje a pantalla para que se seleccione una fila
            JOptionPane.showMessageDialog(null, "Seleccione una Fila", "ADVERTENCIA", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_editarMousePressed

    //Metodo que se ejecuta cuando se presiona el boton eliminar
    private void btn_eliminarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarMousePressed
        int selec = this.jTUsuarios.getSelectedRow();
        if (selec != -1) {
            this.jTUsuarios.clearSelection();
            int resp = JOptionPane.showConfirmDialog(null, "¿Eliminar Usuario"+ this.jTUsuarios.getValueAt(selec, 1) +"?", "Alerta!", JOptionPane.YES_NO_OPTION);
            //Si acepta el mesaje procedemos a eliminar
            if (resp == JOptionPane.YES_OPTION) {
                c_gestionarUsuario cUsuario = new c_gestionarUsuario();
                String personal_Id = String.valueOf(this.jTUsuarios.getValueAt(selec, 0));
                //llamamos al metodo eliminar
                boolean confir = cUsuario.eliminarRegistroUsuario(personal_Id);
                if (confir) {
                    this.mostrarListaUsuarios(cUsuario.getListaPersonal());
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Elija una fila", "ERROR", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btn_eliminarMousePressed

    //boton que se ejecuta cuando se presiona el boton menu
    private void btn_menuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menuMousePressed
        setColor(btn_menu);
       resetColor(btn_agregar);
        resetColor(btn_editar);
        resetColor(btn_eliminar);
        Menu me = new Menu();
        me.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btn_menuMousePressed

    private void jLabel5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel5KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5KeyPressed

    private void btn_agregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregarMouseExited
        resetColor(btn_agregar);
    }//GEN-LAST:event_btn_agregarMouseExited

    private void btn_agregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregarMouseEntered
        // TODO add your handling code here:
        setColor(btn_agregar);
    }//GEN-LAST:event_btn_agregarMouseEntered

    private void btn_editarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editarMouseEntered
        // TODO add your handling code here:
        setColor(btn_editar);
    }//GEN-LAST:event_btn_editarMouseEntered

    private void btn_eliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarMouseEntered
        // TODO add your handling code here:
        setColor(btn_eliminar);
    }//GEN-LAST:event_btn_eliminarMouseEntered

    private void btn_menuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menuMouseEntered
        // TODO add your handling code here:
        setColor(btn_menu);
    }//GEN-LAST:event_btn_menuMouseEntered

    private void btn_editarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editarMouseExited
        // TODO add your handling code here:
        resetColor(btn_editar);
    }//GEN-LAST:event_btn_editarMouseExited

    private void btn_eliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarMouseExited
        // TODO add your handling code here:
        resetColor(btn_eliminar);
    }//GEN-LAST:event_btn_eliminarMouseExited

    private void btn_menuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menuMouseExited
        // TODO add your handling code here:
        resetColor(btn_menu);
    }//GEN-LAST:event_btn_menuMouseExited

    // este el metodo que busca la consulta que se introduce en el jtBuscar
    private void jtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtBuscarKeyReleased

        //si esta seleccionado buscar por nombre ejecuta esto
        if (jcbFiltros.getSelectedItem().equals("Nombre")) {
            //llama al metodo que busca los usuarios por nombre
            this.menUsua.buscarUsuarioPorNombre(this.jtBuscar.getText(), 1);
        }
        //si esta seleccionado buscar por apellido
        if (jcbFiltros.getSelectedItem().equals("Primer Apellido")) {
            //llama al metodo que busca los usuarios por apellido
            this.menUsua.buscarUsuarioPorNombre(this.jtBuscar.getText(), 2);
        }
        if (jcbFiltros.getSelectedItem().equals("Matricula")) {
            //llama al metodo que busca los usuarios por Matricula
            this.menUsua.buscarUsuarioPorNombre(this.jtBuscar.getText(), 3);
        }
    }//GEN-LAST:event_jtBuscarKeyReleased

    //metodo que direcciona el cursor a el buscador
    private void jcbFiltrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbFiltrosActionPerformed
        jtBuscar.requestFocus();
    }//GEN-LAST:event_jcbFiltrosActionPerformed

    private void jtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtBuscarKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (this.jcbFiltros.getSelectedItem().equals("Matricula")) {
            if (!Character.isDigit(c)) {
                evt.consume();
            }
        } else {
            if (!Character.isLetter(c)) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_jtBuscarKeyTyped

    /**
     * @param args the command line arguments
     */
    public void setColor(JPanel jpanel) {
        jpanel.setBackground(new java.awt.Color(0, 176, 247));
    }

    public void resetColor(JPanel jpanel) {
        jpanel.setBackground(new java.awt.Color(0, 153, 204));
    }

    public void validaciones() {
        validacionUsuario v = new validacionUsuario();
        if (this.jcbFiltros.getSelectedItem().equals("Matricula")) {
            v.validarNumeros(jtBuscar);
            v.limitarCaracteres(jtBuscar, 10);
        }
        if (this.jcbFiltros.getSelectedItem().equals("Nombre")) {
            v.validarLetras(jtBuscar);
            v.limitarCaracteres(jtBuscar, 10);
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(i_gestionarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(i_gestionarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(i_gestionarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(i_gestionarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new i_gestionarUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_agregar;
    private javax.swing.JPanel btn_editar;
    private javax.swing.JPanel btn_eliminar;
    private javax.swing.JPanel btn_menu;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTUsuarios;
    private javax.swing.JComboBox<String> jcbFiltros;
    private javax.swing.JTextField jtBuscar;
    // End of variables declaration//GEN-END:variables

}
