package GestionarPersonal;

import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.ResultSet;
import javax.swing.JTextField;

public class i_EditarPersonal extends javax.swing.JFrame {

    private String personal_id;
    private boolean mostrar = true;
    private final c_EditarPersonal eP;
    private i_gestionarPersonal personal;
    private final Validaciones val;

    public i_EditarPersonal() {
        initComponents();
        this.setResizable(false);
        this.val = new Validaciones();
        this.eP = new c_EditarPersonal();
        this.jComboBox1.removeAllItems();
        this.jComboBox1.addItem("Encargado");
        this.jComboBox1.addItem("Auxiliar");
        this.jTextField9.setVisible(false);
    }

    public void verficaciones() {

        //limitar que solo sean caracteres del alfabeto
        this.val.soloLetras(this.jtNombre);
        this.val.soloLetras(this.jtPrimerApellido);
        this.val.soloLetras(this.jtSegundoApellido);
        this.val.soloNumeros(this.jtTelefono);

        //limitar los caracteres
        this.val.limitarNumeros(this.jtTelefono, 10);
        this.val.limitarNumeros(this.jtNombre, 20);
        this.val.limitarNumeros(this.jtPrimerApellido, 20);
        this.val.limitarNumeros(this.jtSegundoApellido, 20);
        this.val.limitarNumeros(this.jtUsuario, 20);
        this.val.limitarNumeros(this.jtCruzamiento1, 20);
        this.val.limitarNumeros(this.jtCruzamiento2, 20);
        this.val.limitarNumeros(this.jtCodigoPostal, 4);
    }

    public void setGestionarPersonal(i_gestionarPersonal personal) {
        this.personal = personal;
    }

    public void cargarDatosPersonal(ResultSet datos) {
        try {
            while (datos.next()) {
                this.personal_id = datos.getString("personal_id");
                this.jtNombre.setText(datos.getString("personal_nombre"));
                this.jtPrimerApellido.setText(datos.getString("personal_primer_apellido"));
                this.jtSegundoApellido.setText(datos.getString("personal_segundo_apellido"));
                this.jtCalle.setText(datos.getString("personal_calle"));
                this.jtTelefono.setText(datos.getString("personal_telefono"));
                this.jtColonia.setText(datos.getString("personal_colonia"));
                this.jtUsuario.setText(datos.getString("personal_usuario"));
                this.jtPassword.setText(datos.getString("personal_password"));
                this.jComboBox1.setSelectedItem(datos.getString("personal_tipopersonal"));
                this.jtCruzamiento1.setText(datos.getString("cruzamiento_1"));
                this.jtCruzamiento2.setText(datos.getString("cruzamiento_2"));
                this.jtCodigoPostal.setText(String.valueOf(datos.getInt("codigo_postal")));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtPrimerApellido = new javax.swing.JTextField();
        jtSegundoApellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtTelefono = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtCalle = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtColonia = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jtCruzamiento1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jtCruzamiento2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jtCodigoPostal = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jtUsuario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jtPassword = new javax.swing.JPasswordField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));

        jLabel12.setText("Actualizar Personal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(jLabel12)
                .addContainerGap(287, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 60));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos personales"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Nombre");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 30, -1, -1));

        jtNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtNombreFocusGained(evt);
            }
        });
        jPanel2.add(jtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 27, 150, -1));

        jLabel3.setText("Primer apellido");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 61, -1, -1));

        jLabel4.setText("Segundo apellido");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 92, -1, -1));

        jtPrimerApellido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtPrimerApellidoFocusGained(evt);
            }
        });
        jPanel2.add(jtPrimerApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 58, 150, -1));
        jPanel2.add(jtSegundoApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 89, 150, -1));

        jLabel6.setText("Telefono");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 123, -1, -1));
        jPanel2.add(jtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 120, 150, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 330, 190));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos domiciliarios"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Calle principal");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));
        jPanel3.add(jtCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 150, -1));

        jLabel5.setText("Colonia");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));
        jPanel3.add(jtColonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 150, -1));

        jLabel13.setText("Primer cruzamiento");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));
        jPanel3.add(jtCruzamiento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 140, -1));

        jLabel14.setText("Segundo cruzamiento");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));
        jPanel3.add(jtCruzamiento2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 140, -1));

        jLabel15.setText("Codigo postal");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));
        jPanel3.add(jtCodigoPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 100, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 280, 190));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de cuenta"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtUsuarioFocusGained(evt);
            }
        });
        jPanel4.add(jtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 138, -1));

        jLabel7.setText("Usuario");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 30, -1, -1));

        jLabel8.setText("Password");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 58, -1, -1));

        jLabel9.setText("Tipo de usuario");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 94, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel4.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 140, -1));

        jtPassword.setText("jPasswordField1");
        jPanel4.add(jtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 140, -1));

        jTextField8.setText("jTextField8");
        jPanel4.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 160, -1));

        jTextField9.setText("jTextField9");
        jPanel4.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 140, -1));

        jLabel11.setText("Mostrar");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel11MousePressed(evt);
            }
        });
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 330, 130));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Refresh_40px.png"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel10MousePressed(evt);
            }
        });

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Cancel_48px.png"))); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel16MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(257, 257, 257)
                .addComponent(jLabel10)
                .addGap(33, 33, 33)
                .addComponent(jLabel16)
                .addContainerGap(250, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 630, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MousePressed
        // TODO add your handling code here:
        if (this.mostrar) {
            this.jtPassword.setVisible(false);
            this.jTextField9.setText(this.jtPassword.getText());
            this.jTextField9.setVisible(true);
            this.mostrar = false;
        } else {
            this.jtPassword.setVisible(true);
            this.jTextField9.setVisible(false);
            this.mostrar = true;
        }
    }//GEN-LAST:event_jLabel11MousePressed

    private void jLabel10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MousePressed
        // TODO add your handling code here:

        String password = "";

        JTextField[] datos = new JTextField[3];
        Object[] datosAct = new Object[13];
        datos[0] = this.jtNombre;
        datos[1] = this.jtPrimerApellido;
        datos[2] = this.jtUsuario;

        boolean vacio = true;

        for (int i = 0; i < datos.length; i++) {
            if (datos[i].getText().length() == 0) {
                vacio = false;
                datos[i].setBackground(Color.red);
            }
        }

        if (vacio) {

            if (this.jtPrimerApellido.isVisible()) {
                password = this.jtPassword.getText();
            } else {
                if (this.jTextField9.isVisible()) {
                    password = this.jTextField9.getText();
                }
            }

            datosAct[0] = this.personal_id;
            datosAct[1] = this.jtNombre.getText();
            datosAct[2] = this.jtPrimerApellido.getText();
            datosAct[3] = this.jtSegundoApellido.getText();
            datosAct[4] = this.jtCalle.getText();
            datosAct[5] = this.jtTelefono.getText();
            datosAct[6] = this.jtColonia.getText();
            datosAct[7] = this.jtUsuario.getText();
            datosAct[8] = password;
            datosAct[9] = this.jComboBox1.getSelectedItem();
            datosAct[10] = this.jtCruzamiento1.getText();
            datosAct[11] = this.jtCruzamiento1.getText();
            datosAct[12] = this.jtCodigoPostal.getText();

            this.eP.setGestionarPersonal(this.personal);
            this.eP.setIep(this);
            this.eP.actualizarPersonal(datosAct);
        }
    }//GEN-LAST:event_jLabel10MousePressed

    private void jtNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNombreFocusGained
        // TODO add your handling code here:
        this.jtNombre.setBackground(Color.WHITE);
    }//GEN-LAST:event_jtNombreFocusGained

    private void jtUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtUsuarioFocusGained
        // TODO add your handling code here:
        this.jtUsuario.setBackground(Color.WHITE);
    }//GEN-LAST:event_jtUsuarioFocusGained

    private void jtPrimerApellidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtPrimerApellidoFocusGained
        // TODO add your handling code here:
        this.jtPrimerApellido.setBackground(Color.WHITE);
    }//GEN-LAST:event_jtPrimerApellidoFocusGained

    private void jLabel16MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MousePressed
        // TODO add your handling code here:
        
        this.personal.setBanderaUsoEditar(true);
        this.dispose();
    }//GEN-LAST:event_jLabel16MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(i_EditarPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(i_EditarPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(i_EditarPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(i_EditarPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new i_EditarPersonal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField jtCalle;
    private javax.swing.JTextField jtCodigoPostal;
    private javax.swing.JTextField jtColonia;
    private javax.swing.JTextField jtCruzamiento1;
    private javax.swing.JTextField jtCruzamiento2;
    private javax.swing.JTextField jtNombre;
    private javax.swing.JPasswordField jtPassword;
    private javax.swing.JTextField jtPrimerApellido;
    private javax.swing.JTextField jtSegundoApellido;
    private javax.swing.JTextField jtTelefono;
    private javax.swing.JTextField jtUsuario;
    // End of variables declaration//GEN-END:variables
}
